application: antscoper
version: 1

runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- messages
- vacancy\.js
- README\.md

handlers:
- url: /(.*\.(gif|png|jpg|ico))
  static_files: \1
  upload: .*\.(gif|png|jpg|ico)
- url: /scrape
  script: scrape.py
  secure: always
- url: .*
  script: main.app
  secure: always
